---
AWSTemplateFormatVersion: '2010-09-09'
Description: Snyk resources required to provision into your account
Outputs:
  AWSRegion:
    Description: The AWS region for your Snyk intgration
    Value: !Sub ${AWS::Region}
  SnykECRIntegrationRole:
    Description: Snyk ECR Integration Role ARN
    Value: !GetAtt SnykECRIntegrationRole.Arn
  SnykLambdaIntegrationRole:
    Description: Snyk Lambda Integration Role ARN
    Value: !GetAtt SnykLambdaIntegrationRole.Arn
  Version:
    Description: Snyk Account Capabilities Version
    Value: 1.0.1
Metadata:
  LICENSE: Apache License, Version 2.0
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Snyk
        Parameters:
          - SnykExternalId
      - Label:
          default: AWS Quick Start configuration
        Parameters:
          - QSS3BucketName
          - QSS3KeyPrefix
    ParameterLabels:
      SnykExternalId:
        default: Snyk Organization ID
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
Parameters:
  SnykExternalId:
    Description: You may find this by logging into https://app.snyk.io and navigate to Settings.
    Type: String
    AllowedPattern: '[a-z0-9-]{36}'
    MinLength: 1
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription:
      Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: aws-quickstart
    Description:
      S3 bucket name for the Quick Start assets. This string can include
      numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start
      or end with a hyphen (-).
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/.]*$
    ConstraintDescription:
      Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), dots(.) and forward slash (/).
    Default: quickstart-snyk-security/
    Description:
      S3 key prefix for the Quick Start assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), dots(.) and
      forward slash (/).
    Type: String
Resources:
  SnykECRIntegrationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::198361731867:root
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref SnykExternalId
      Path: /snyk/
      Policies:
        - PolicyName: AmazonEC2ContainerRegistryReadOnlyForSnyk
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  [
                    'ecr:GetLifecyclePolicyPreview',
                    'ecr:GetDownloadUrlForLayer',
                    'ecr:BatchGetImage',
                    'ecr:DescribeImages',
                    'ecr:GetAuthorizationToken',
                    'ecr:DescribeRepositories',
                    'ecr:ListTagsForResource',
                    'ecr:ListImages',
                    'ecr:BatchCheckLayerAvailability',
                    'ecr:GetRepositoryPolicy',
                    'ecr:GetLifecyclePolicy'
                  ]
                Resource: '*'
  SnykLambdaIntegrationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::198361731867:root
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref SnykExternalId
      Path: /snyk/
      Policies:
        - PolicyName: SnykReadOnlyForLambda
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  [
                    'lambda:ListFunctions',
                    'lambda:GetFunction',
                    'lambda:ListAliases',
                    'lambda:GetAccountSettings'
                  ]
                Resource: '*'
